micronaut:
  application:
    name: desafiopix

grpc:
  server:
    port: 50051
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/keymanagerdb
    driverClassName: org.postgresql.Driver
    username: keymanager
    password: 1234567
    schema-generate: CREATE_DROP

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

#datasources:
#  default:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
#
#jpa:
#  default:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update